name: build-deploy-assets

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: twtug/lkmpg

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make all
          make html
          tar zcvf lkmpg-html.tar.gz ./html
      - name: Delete old release asset
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ github.token }}
          fail-if-no-assets: false
          fail-if-no-release: false
          tag: latest
          assets: |
            lkmpg.pdf
            lkmpg-html.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v0.1.8
        with:
          files: |
            lkmpg.pdf
            lkmpg-html.tar.gz
          tag_name: "latest"
          prerelease: true
